Comment out git operations in Jenkinsfile

diff --git a/tests/ci/Jenkinsfile.ort b/tests/ci/Jenkinsfile.ort
--- a/tests/ci/Jenkinsfile.ort
+++ b/tests/ci/Jenkinsfile.ort
@@ -264,9 +264,9 @@ pipeline {
                     git add -f logs/log_opnReqTest_ursa
                     git add logs/RegressionTests_ursa.log
                     git commit -m "Ursa ORT FAILED.\n\n\n on-behalf-of @ufs-community <ecc.platform@noaa.gov>"
-                    git config pull.rebase false
-                    git pull sshorigin $FORK_BRANCH
-                    git push sshorigin HEAD:$FORK_BRANCH
+#                    git config pull.rebase false
+#                    git pull sshorigin $FORK_BRANCH
+#                    git push sshorigin HEAD:$FORK_BRANCH
                   echo "Ursa Failed"
                     '''
                   }
@@ -295,29 +295,42 @@ pipeline {
               steps{
                 cleanWs()
                 checkout scm
-                sh '''
+                script{
+                sh 'echo "" > $WORKSPACE/tests/error.log'
+                def exitCode = sh(
+                script: '''
+                  set +e
+
+                    log_error() {
+                        echo "ERROR in $1 on line $2" >> $WORKSPACE/tests/error.log
+                    }
+
                   git submodule update --init --recursive
                   cd tests/fv3_conf
                   sed 's/#SBATCH --time=.*/#SBATCH --time=02:00:00/g' -i fv3_slurm.IN_hercules
                   cd ..
-                  export machine=${NODE_NAME}
-                  export PATH=$PATH:~/bin
-                  export SSH_ORIGIN=$(curl --silent https://api.github.com/repos/arbetter/ufs-weather-model/pulls/$CHANGE_ID | jq -r '.head.repo.ssh_url')
-                  export FORK_BRANCH=$(curl --silent https://api.github.com/repos/arbetter/ufs-weather-model/pulls/$CHANGE_ID | jq -r '.head.ref')
                   export ACCNR=epic
-                  export GIT_OWNER=$(echo $GIT_URL | cut -d '/' -f4)
-                  export GIT_REPO_NAME=$(echo $GIT_URL | cut -d '/' -f5 | cut -d '.' -f1)
-                  echo "GIT_OWNER ${GIT_OWNER}"
-                  echo "GIT_REPO_NAME ${GIT_REPO_NAME}"
-
                   pwd
-                  ./opnReqTest -n regional_control -a ${ACCNR} -c bit,dcp,thr
-                  cd logs/
-                  # change "cp" to "mv" to be tighter on logfiles existence (prevents using logfiles from a previous run)
+#                  ./opnReqTest -n regional_control -a ${ACCNR} -c bit,dcp,thr
+                  ./opnReqTest -n regional_control -a ${ACCNR} -c bit,dcp,thr -x || log_error OpenReqTest $LINENO
+                  cd $WORKSPACE/tests/logs/
                   mv OpnReqTests_regional_control_hercules.log $WORKSPACE/..
                   cd ..
                   pwd
-                '''
+                   [ -s $WORKSPACE/tests/error.log ] && rm $WORKSPACE/tests/error.log && exit 1 || exit 0 
+                  ''',
+                  returnStatus: true
+                ) // exitCode
+                echo "Hercules regional_control exit code: ${exitCode}"
+                if (exitCode == 0) {
+                  echo "Pipeline continuing normally."
+                } else {
+                  echo "Handling failure in Groovy. Changing stage color..."
+                  currentBuild.result = 'FAILURE'
+                  region_result = 'FAILURE'
+                }
+                } //script
+
               } // End of steps
             } // End of stage regional_control
             
@@ -347,7 +360,19 @@ pipeline {
                   mv OpnReqTests_control_p8_hercules.log $WORKSPACE/..
                   cd ..
                   pwd
-                '''
+                  [ -s $WORKSPACE/tests/error.log ] && rm $WORKSPACE/tests/error.log && exit 1 || exit 0    
+                  ''',
+                  returnStatus: true
+                ) // exitCode
+                echo "Hercules control_p8 exit code: ${exitCode}"
+                if (exitCode == 0) {
+                  echo "Pipeline continuing normally."
+                } else {
+                  echo "Handling failure in Groovy. Changing stage color..."
+                  currentBuild.result = 'FAILURE'
+                  control_result = 'FAILURE'
+                }
+                } //script
               } // End of steps
             } // End of stage control_p8
             
@@ -450,9 +475,9 @@ pipeline {
                     git add -f logs/log_opnReqTest_hercules
                     git add logs/RegressionTests_hercules.log
                     git commit -m "Hercules ORT FAILED.\n\n\n on-behalf-of @ufs-community <ecc.platform@noaa.gov>"
-                    git config pull.rebase false                    
-                    git pull sshorigin $FORK_BRANCH
-                    git push sshorigin HEAD:$FORK_BRANCH
+   #                 git config pull.rebase false                    
+   #                 git pull sshorigin $FORK_BRANCH
+   #                 git push sshorigin HEAD:$FORK_BRANCH
                   echo "Hercules Failure"
                     '''
                   }
@@ -482,29 +507,43 @@ pipeline {
               steps{
                 cleanWs()
                 checkout scm
-                sh '''
+                script{
+                sh 'echo "" > $WORKSPACE/tests/error.log'
+                def exitCode = sh(
+                script: '''
+                  set +e
+
+                    log_error() {
+                        echo "ERROR in $1 on line $2" >> $WORKSPACE/tests/error.log
+                    }
+
                   git submodule update --init --recursive
                   cd tests/fv3_conf
                   sed 's/#SBATCH --time=.*/#SBATCH --time=02:00:00/g' -i fv3_slurm.IN_orion
                   cd ..
-                  export machine=${NODE_NAME}
-                  export PATH=$PATH:~/bin
-                  export SSH_ORIGIN=$(curl --silent https://api.github.com/repos/arbetter/ufs-weather-model/pulls/$CHANGE_ID | jq -r '.head.repo.ssh_url')
-                  export FORK_BRANCH=$(curl --silent https://api.github.com/repos/arbetter/ufs-weather-model/pulls/$CHANGE_ID | jq -r '.head.ref')
                   export ACCNR=epic
-                  export GIT_OWNER=$(echo $GIT_URL | cut -d '/' -f4)
-                  export GIT_REPO_NAME=$(echo $GIT_URL | cut -d '/' -f5 | cut -d '.' -f1)
-                  echo "GIT_OWNER ${GIT_OWNER}"
-                  echo "GIT_REPO_NAME ${GIT_REPO_NAME}"
-
                   pwd
-                  ./opnReqTest -n regional_control -a ${ACCNR} -c bit,dcp,thr
-                  cd logs/
+#                  ./opnReqTest -n regional_control -a ${ACCNR} -c bit,dcp,thr
+                  ./opnReqTest -n regional_control -a ${ACCNR} -c bit,dcp,thr -x || log_error OpenReqTest $LINENO
+                  cd $WORKSPACE/tests/logs/
                   # change "cp" to "mv" to be tighter on logfiles existence (prevents using logfiles from a previous run)
                   mv OpnReqTests_regional_control_orion.log $WORKSPACE/..
                   cd ..
                   pwd
-                '''
+                     [ -s $WORKSPACE/tests/error.log ] && rm $WORKSPACE/tests/error.log && exit 1 || exit 0 
+                  ''',
+                  returnStatus: true
+                ) // exitCode
+                echo "Orion regional_control exit code: ${exitCode}"
+                if (exitCode == 0) {
+                  echo "Pipeline continuing normally."
+                } else {
+                  echo "Handling failure in Groovy. Changing stage color..."
+                  currentBuild.result = 'FAILURE'
+                  region_result = 'FAILURE'
+                }
+                } //script
+
               } // End of steps
             } // End of stage regional_control
             
@@ -534,7 +573,19 @@ pipeline {
                   mv OpnReqTests_control_p8_orion.log $WORKSPACE/..
                   cd ..
                   pwd
-                '''
+                  [ -s $WORKSPACE/tests/error.log ] && rm $WORKSPACE/tests/error.log && exit 1 || exit 0    
+                  ''',
+                  returnStatus: true
+                ) // exitCode
+                echo "Orion control_p8 exit code: ${exitCode}"
+                if (exitCode == 0) {
+                  echo "Pipeline continuing normally."
+                } else {
+                  echo "Handling failure in Groovy. Changing stage color..."
+                  currentBuild.result = 'FAILURE'
+                  control_result = 'FAILURE'
+                }
+                } //script
               } // End of steps
             } // End of stage control_p8
             
@@ -637,9 +688,9 @@ pipeline {
                     git add -f logs/log_opnReqTest_orion
                     git add logs/RegressionTests_orion.log
                     git commit -m "Orion ORT FAILED.\n\n\n on-behalf-of @ufs-community <ecc.platform@noaa.gov>"
-                    git config pull.rebase false
-                    git pull sshorigin $FORK_BRANCH
-                    git push sshorigin HEAD:$FORK_BRANCH
+   #                 git config pull.rebase false
+   #                git pull sshorigin $FORK_BRANCH
+   #                 git push sshorigin HEAD:$FORK_BRANCH
                   echo "Orion Failure"
                     '''
                   }
